services:

  web:
    build: ./
    volumes:
      - ./src:/app/src/
    ports:
      - 8080:80
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/foo
    depends_on:
      - db

  db:
    image: postgres:15.3
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=foo
